export type MemeCard = {
  id: string;
  stamp: string;
  src: string;
  file: string;
  alt: string;
  caption: string;
};

export const memes: MemeCard[] = [
  {
    id: "rebuttal",
    stamp: "01",
    src: "/memes/01-rebuttal.jpg",
    file: "jrock-rebuttal.jpg",
    alt: "Jamie’s Pet Rock flexing in a navy Bitcoin tie and matching sneakers",
    caption: "Jamie said Bitcoin does nothing. The rock filed a rebuttal.",
  },
  {
    id: "lining",
    stamp: "02",
    src: "/memes/02-lining.jpg",
    file: "jrock-lining.jpg",
    alt: "The rock opening a black coat lined with glowing green candles",
    caption: "The lining is all candles. The rock does not share its coat.",
  },
  {
    id: "here-we-go",
    stamp: "03",
    src: "/memes/03-here-we-go.jpg",
    file: "jrock-here-we-go.jpg",
    alt: "The rock walking down a sunset alley, seen from behind",
    caption: "Ah shit here we go again.",
  },
  {
    id: "suburb",
    stamp: "04",
    src: "/memes/04-suburb.jpg",
    file: "jrock-suburb.jpg",
    alt: "A giant pet rock looming over a suburb in a dust storm",
    caption: "They called it a pet rock. The suburb disagrees.",
  },
  {
    id: "chart-eye",
    stamp: "05",
    src: "/memes/05-chart-eye.jpg",
    file: "jrock-chart-eye.jpg",
    alt: "Close-up of the rock’s eye with a green candlestick chart in the pupil",
    caption: "The rock only sees one chart.",
  },
  {
    id: "first-class",
    stamp: "06",
    src: "/memes/06-first-class.jpg",
    file: "jrock-first-class.jpg",
    alt: "The rock hanging onto an airplane window shade above the clouds",
    caption: "First class. Still a rock.",
  },
  {
    id: "paper-hands",
    stamp: "07",
    src: "/memes/07-paper-hands.jpg",
    file: "jrock-paper-hands.jpg",
    alt: "The rock standing in a desert sunset beside a paper-hands figure",
    caption: "Paper hands had a meeting. The rock took minutes.",
  },
  {
    id: "red-rings",
    stamp: "08",
    src: "/memes/08-red-rings.jpg",
    file: "jrock-red-rings.jpg",
    alt: "The rock panicking with hands on its head inside red radar rings",
    caption: "Red rings. The rock is not selling.",
  },
  {
    id: "green-rings",
    stamp: "09",
    src: "/memes/09-green-rings.jpg",
    file: "jrock-green-rings.jpg",
    alt: "The rock smiling inside green radar rings",
    caption: "Green rings. The rock has processed the news.",
  },
  {
    id: "air-support",
    stamp: "10",
    src: "/memes/10-air-support.jpg",
    file: "jrock-air-support.jpg",
    alt: "The rock in a fighter jet cockpit with wingmen in the sky",
    caption: "Air support. The rock does not fly commercial.",
  },
  {
    id: "intern",
    stamp: "11",
    src: "/memes/11-intern.jpg",
    file: "jrock-intern.jpg",
    alt: "The rock at a trading desk with a hooded intern watching from behind",
    caption: "The intern is watching. The rock is working.",
  },
  {
    id: "night",
    stamp: "12",
    src: "/memes/12-night.jpg",
    file: "jrock-night.jpg",
    alt: "The rock dressed as a dark knight in a cape and cowl",
    caption: "I am the night. Also a rock.",
  },
  {
    id: "beauty-sleep",
    stamp: "13",
    src: "/memes/13-beauty-sleep.jpg",
    file: "jrock-beauty-sleep.jpg",
    alt: "The rock in bed under a navy blanket still wearing its Bitcoin tie",
    caption: "Diamond hands need beauty sleep.",
  },
  {
    id: "briefing",
    stamp: "14",
    src: "/memes/14-briefing.jpg",
    file: "jrock-briefing.jpg",
    alt: "The rock presenting on a bright screen to a dark boardroom",
    caption: "The board asked for a pet. They got a briefing.",
  },
  {
    id: "calling",
    stamp: "15",
    src: "/memes/15-calling.jpg",
    file: "jrock-calling.jpg",
    alt: "A phone screen showing the rock in bed with JROCK is calling",
    caption: "JROCK is calling. Accept the charges.",
  },
  {
    id: "hedge",
    stamp: "16",
    src: "/memes/16-hedge.jpg",
    file: "jrock-hedge.jpg",
    alt: "The rock in a navy Bitcoin tie holding a lit joint",
    caption: "The rock is hedging. Recreationally.",
  },
  {
    id: "system",
    stamp: "17",
    src: "/memes/17-system.jpg",
    file: "jrock-system.jpg",
    alt: "The rock pulling a lever while watching a candlestick chart",
    caption: "One more pull. The rock has a system.",
  },
  {
    id: "no-motor",
    stamp: "18",
    src: "/memes/18-no-motor.png",
    file: "jrock-no-motor.png",
    alt: "The rock riding a tiny bicycle with a serious face",
    caption: "No motor. Still faster than your thesis.",
  },
  {
    id: "premiere",
    stamp: "19",
    src: "/memes/19-premiere.png",
    file: "jrock-premiere.png",
    alt: "The rock on a red carpet in a navy Bitcoin tie with cameras in the dark",
    caption: "Red carpet. The rock brought Bitcoin.",
  },
  {
    id: "throne",
    stamp: "20",
    src: "/memes/20-throne.jpg",
    file: "jrock-throne.jpg",
    alt: "The rock in a white robe on a gold Bitcoin throne holding a Bitcoin coin",
    caption: "The throne is gold. The rock is still a rock.",
  },
  {
    id: "hodl",
    stamp: "21",
    src: "/memes/21-hodl.jpg",
    file: "jrock-hodl.jpg",
    alt: "A giant hand squeezing the rock with HODL $JROCK tattooed on the wrist",
    caption: "HODL $JROCK. The rock is not for sale.",
  },
  {
    id: "stairs",
    stamp: "22",
    src: "/memes/22-stairs.png",
    file: "jrock-stairs.png",
    alt: "The rock walking up a giant green chart arrow in Bitcoin sneakers",
    caption: "The chart went up. The rock walked it.",
  },
  {
    id: "hoodie",
    stamp: "23",
    src: "/memes/23-hoodie.png",
    file: "jrock-hoodie.png",
    alt: "The rock wearing glasses and a black Binance hoodie, holding a small yellow logo",
    caption: "Binance sent merch. The rock kept the sneakers.",
  },
  {
    id: "posted",
    stamp: "24",
    src: "/memes/24-posted.png",
    file: "jrock-posted.png",
    alt: "The rock with brown hair in a black X jacket giving a thumbs up",
    caption: "Posted. The rock does not delete tweets.",
  },
  {
    id: "executive",
    stamp: "25",
    src: "/memes/25-executive.png",
    file: "jrock-executive.png",
    alt: "The rock with blonde hair in a navy suit holding a Bitcoin coin and giving a thumbs up",
    caption: "The rock is considering a run. For Bitcoin.",
  },
  {
    id: "orbit",
    stamp: "26",
    src: "/memes/26-orbit.png",
    file: "jrock-orbit.png",
    alt: "The rock floating in space with a glowing aura and closed eyes",
    caption: "The rock does not need oxygen. Or a thesis.",
  },
  {
    id: "evidence",
    stamp: "27",
    src: "/memes/27-evidence.jpg",
    file: "jrock-evidence.jpg",
    alt: "Two-panel detective rock inspecting a red candle, then swapping in a green candle",
    caption: "The rock found a red candle. It brought a green one.",
  },
  {
    id: "float",
    stamp: "28",
    src: "/memes/28-float.jpg",
    file: "jrock-float.jpg",
    alt: "The rock in a white astronaut suit floating past dollar bills and waving at the moon",
    caption: "Zero gravity. Still stacking.",
  },
  {
    id: "elevator",
    stamp: "29",
    src: "/memes/29-elevator.jpg",
    file: "jrock-elevator.jpg",
    alt: "The rock grinning from a closing elevator beside a Bitcoin tulip",
    caption: "Going up. The rock already pressed the button.",
  },
  {
    id: "split",
    stamp: "30",
    src: "/memes/30-split.jpg",
    file: "jrock-split.jpg",
    alt: "Split portrait of the rock in color with a gold Bitcoin pin and in black and white with a silver pin",
    caption: "Color or grayscale. Same rock. Same thesis.",
  },
  {
    id: "bears",
    stamp: "31",
    src: "/memes/31-bears.jpg",
    file: "jrock-bears.jpg",
    alt: "The rock aiming a scope at a crying bear on a blue-sky background",
    caption: "The bears were talking. The rock stopped listening.",
  },
  {
    id: "aurora",
    stamp: "32",
    src: "/memes/32-aurora.jpg",
    file: "jrock-aurora.jpg",
    alt: "The rock sitting on a cliff in a navy scarf watching the northern lights",
    caption: "The rock sat still. The sky did the work.",
  },
  {
    id: "peek",
    stamp: "33",
    src: "/memes/33-peek.png",
    file: "jrock-peek.png",
    alt: "The rock peeking through a hole in the dark with a Bitcoin tie",
    caption: "The rock is watching. You were saying?",
  },
  {
    id: "xray",
    stamp: "34",
    src: "/memes/34-xray.jpg",
    file: "jrock-xray.jpg",
    alt: "X-ray of the rock showing a glowing skeleton, Bitcoin tie, and sneakers",
    caption: "X-ray confirmed. Still a rock. Still Bitcoin.",
  },
  {
    id: "oath",
    stamp: "35",
    src: "/memes/35-oath.jpg",
    file: "jrock-oath.jpg",
    alt: "The rock in a black robe raising one hand and holding a paper like a sworn statement",
    caption: "The rock swears. Bitcoin does something.",
  },
  {
    id: "gm",
    stamp: "36",
    src: "/memes/36-gm.jpg",
    file: "jrock-gm.jpg",
    alt: "The rock holding a steaming coffee mug that says GM",
    caption: "GM. The rock already drank yours.",
  },
  {
    id: "mason",
    stamp: "37",
    src: "/memes/37-mason.jpg",
    file: "jrock-mason.jpg",
    alt: "The rock laying glowing green bricks with a trowel and holding a green block",
    caption: "The rock is building. Green candles only.",
  },
  {
    id: "sprint",
    stamp: "38",
    src: "/memes/38-sprint.jpg",
    file: "jrock-sprint.jpg",
    alt: "The rock sprinting in Bitcoin sneakers with a city streaking behind it",
    caption: "The rock does not jog. It sprints the thesis.",
  },
  {
    id: "bags",
    stamp: "39",
    src: "/memes/39-bags.jpg",
    file: "jrock-bags.jpg",
    alt: "The rock reclining on a pile of gold Bitcoin coins with hands behind its head",
    caption: "The rock sat down. The coins did the rest.",
  },
  {
    id: "lambo",
    stamp: "40",
    src: "/memes/40-lambo.jpg",
    file: "jrock-lambo.jpg",
    alt: "The rock washing a yellow Lamborghini with a sponge and a soapy yellow bucket",
    caption: "The rock washes its own bags.",
  },
  {
    id: "toy",
    stamp: "41",
    src: "/memes/41-toy.jpg",
    file: "jrock-toy.jpg",
    alt: "A voxel pet rock sitting in a giant pixelated hand wearing a Bitcoin tie and sneakers",
    caption: "Picked up. The rock is still holding.",
  },
  {
    id: "chess",
    stamp: "42",
    src: "/memes/42-chess.jpg",
    file: "jrock-chess.jpg",
    alt: "The rock on a chessboard holding a red knight with green kings around it",
    caption: "The rock does not play. It takes pieces.",
  },
  {
    id: "gi",
    stamp: "43",
    src: "/memes/43-gi.jpg",
    file: "jrock-gi.jpg",
    alt: "The rock in a yellow martial arts gi pointing at the camera",
    caption: "The rock chose you. Fight.",
  },
  {
    id: "fine",
    stamp: "44",
    src: "/memes/44-fine.png",
    file: "jrock-fine.png",
    alt: "The rock sitting with a Bitcoin coffee mug saying this is fine",
    caption: "This is fine. The rock already knew.",
  },
  {
    id: "cockpit",
    stamp: "45",
    src: "/memes/45-cockpit.jpg",
    file: "jrock-cockpit.jpg",
    alt: "The rock in a fighter-jet cockpit wearing a helmet and headset",
    caption: "Top gun. Still a rock.",
  },
  {
    id: "unchained",
    stamp: "46",
    src: "/memes/46-unchained.jpg",
    file: "jrock-unchained.jpg",
    alt: "The rock in a yellow gi screaming while ripping metal chains apart",
    caption: "The rock is not locked. The market is.",
  },
];
