export type MemeCard = {
  id: string;
  stamp: string;
  src: string;
  file: string;
  alt: string;
  caption: string;
};

export const memes: MemeCard[] = [
  {
    id: "rebuttal",
    stamp: "01",
    src: "/memes/01-rebuttal.jpg",
    file: "jrock-rebuttal.jpg",
    alt: "Jamie’s Pet Rock flexing in a navy Bitcoin tie and matching sneakers",
    caption: "Jamie said Bitcoin does nothing. The rock filed a rebuttal.",
  },
  {
    id: "lining",
    stamp: "02",
    src: "/memes/02-lining.jpg",
    file: "jrock-lining.jpg",
    alt: "The rock opening a black coat lined with glowing green candles",
    caption: "The lining is all candles. The rock does not share its coat.",
  },
  {
    id: "here-we-go",
    stamp: "03",
    src: "/memes/03-here-we-go.jpg",
    file: "jrock-here-we-go.jpg",
    alt: "The rock walking down a sunset alley, seen from behind",
    caption: "Ah shit here we go again.",
  },
  {
    id: "suburb",
    stamp: "04",
    src: "/memes/04-suburb.jpg",
    file: "jrock-suburb.jpg",
    alt: "A giant pet rock looming over a suburb in a dust storm",
    caption: "They called it a pet rock. The suburb disagrees.",
  },
  {
    id: "chart-eye",
    stamp: "05",
    src: "/memes/05-chart-eye.jpg",
    file: "jrock-chart-eye.jpg",
    alt: "Close-up of the rock’s eye with a green candlestick chart in the pupil",
    caption: "The rock only sees one chart.",
  },
  {
    id: "first-class",
    stamp: "06",
    src: "/memes/06-first-class.jpg",
    file: "jrock-first-class.jpg",
    alt: "The rock hanging onto an airplane window shade above the clouds",
    caption: "First class. Still a rock.",
  },
  {
    id: "paper-hands",
    stamp: "07",
    src: "/memes/07-paper-hands.jpg",
    file: "jrock-paper-hands.jpg",
    alt: "The rock standing in a desert sunset beside a paper-hands figure",
    caption: "Paper hands had a meeting. The rock took minutes.",
  },
  {
    id: "red-rings",
    stamp: "08",
    src: "/memes/08-red-rings.jpg",
    file: "jrock-red-rings.jpg",
    alt: "The rock panicking with hands on its head inside red radar rings",
    caption: "Red rings. The rock is not selling.",
  },
  {
    id: "green-rings",
    stamp: "09",
    src: "/memes/09-green-rings.jpg",
    file: "jrock-green-rings.jpg",
    alt: "The rock smiling inside green radar rings",
    caption: "Green rings. The rock has processed the news.",
  },
  {
    id: "air-support",
    stamp: "10",
    src: "/memes/10-air-support.jpg",
    file: "jrock-air-support.jpg",
    alt: "The rock in a fighter jet cockpit with wingmen in the sky",
    caption: "Air support. The rock does not fly commercial.",
  },
  {
    id: "intern",
    stamp: "11",
    src: "/memes/11-intern.jpg",
    file: "jrock-intern.jpg",
    alt: "The rock at a trading desk with a hooded intern watching from behind",
    caption: "The intern is watching. The rock is working.",
  },
  {
    id: "night",
    stamp: "12",
    src: "/memes/12-night.jpg",
    file: "jrock-night.jpg",
    alt: "The rock dressed as a dark knight in a cape and cowl",
    caption: "I am the night. Also a rock.",
  },
  {
    id: "beauty-sleep",
    stamp: "13",
    src: "/memes/13-beauty-sleep.jpg",
    file: "jrock-beauty-sleep.jpg",
    alt: "The rock in bed under a navy blanket still wearing its Bitcoin tie",
    caption: "Diamond hands need beauty sleep.",
  },
  {
    id: "briefing",
    stamp: "14",
    src: "/memes/14-briefing.jpg",
    file: "jrock-briefing.jpg",
    alt: "The rock presenting on a bright screen to a dark boardroom",
    caption: "The board asked for a pet. They got a briefing.",
  },
  {
    id: "calling",
    stamp: "15",
    src: "/memes/15-calling.jpg",
    file: "jrock-calling.jpg",
    alt: "A phone screen showing the rock in bed with JROCK is calling",
    caption: "JROCK is calling. Accept the charges.",
  },
  {
    id: "hedge",
    stamp: "16",
    src: "/memes/16-hedge.jpg",
    file: "jrock-hedge.jpg",
    alt: "The rock in a navy Bitcoin tie holding a lit joint",
    caption: "The rock is hedging. Recreationally.",
  },
  {
    id: "system",
    stamp: "17",
    src: "/memes/17-system.jpg",
    file: "jrock-system.jpg",
    alt: "The rock pulling a lever while watching a candlestick chart",
    caption: "One more pull. The rock has a system.",
  },
  {
    id: "no-motor",
    stamp: "18",
    src: "/memes/18-no-motor.png",
    file: "jrock-no-motor.png",
    alt: "The rock riding a tiny bicycle with a serious face",
    caption: "No motor. Still faster than your thesis.",
  },
];
